baseurl = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "noindex"

[build]
  command = "yarn build"
  publish = "docs/.vuepress/dist/"